service: service-name

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  apiKeys:
    - ${self:service}-${self:provider.stage}

custom:
  webpackIncludeModules: true
  # Uncomment the lines below if you want to have a custom domain name for your service
  # The service will be accessible at https://<domain_name>/<service_name>
  # customDomain:
  #   domainName: ${self:provider.stage}.${env:DOMAIN_NAME}
  #   basePath: ${self:service}
  #   stage: ${self:provider.stage}
  #   createRoute53Record: true
  #   endpointType: 'regional'
  # Uncomment when using serverless-plugin-aws-resolvers. Check documentation for more options
  # awsResolvers:
  # This will have to be false if the resource is being created with serverless
  #   strict: false
  # ess: "https://${aws:ess:service-name:Endpoint, 'www.google.com'}"


functions:
  index:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: get
          private: true
      # Ping every 5 minutes to avoid cold starts
      - schedule:
          rate: rate(5 minutes)
          enabled: true

plugins:
  - serverless-webpack
  - serverless-offline
  # Required for custom domains
  # - serverless-domain-manager
  # Required when using cloudformation pseudo parameters
  # - serverless-pseudo-parameters
  # Required when CF resources need to be resolved
  # - serverless-plugin-aws-resolvers
