service: service-name

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

custom:
  webpackIncludeModules: true


functions:
  index:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: get
      # Ping every 5 minutes to avoid cold starts
      - schedule:
          rate: rate(5 minutes)
          enabled: true

plugins:
  - serverless-webpack
  - serverless-offline

